## Need to adjusted to your environment and requirements
## This is for demo purpose only

configs:
  params:
    server.insecure: true ## only for demo purpose - do not use in production
server:
  podLabels:
    azure.workload.identity/use: "true"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingressClassName: nginx
    hostname: argocd.service.learndevops.in ## will be only reachable if all other components are in place
    pathType: ImplementationSpecific
    tls: true
controller:
  podLabels:
    azure.workload.identity/use: "true"
extraObjects: []
