## Need to adjusted to your environment and requirements
## This is for demo purpose only

configs:
  params:
    server.insecure: true ## only for demo purpose - do not use in production
server:
  podLabels:
    azure.workload.identity/use: "true"
controller:
  podLabels:
    azure.workload.identity/use: "true"
