ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: sample-app.dev.service.learndevops.in
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: sample-app-tls
     hosts:
       - sample-app.dev.service.learndevops.in
